// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAoZRtwDGgBoB1SFoYeAAttuJVc9o1L-Q',
    appId: '1:25069081784:web:1fab44f0b5ccff56d6d04d',
    messagingSenderId: '25069081784',
    projectId: 'synew-gym',
    authDomain: 'synew-gym.firebaseapp.com',
    storageBucket: 'synew-gym.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQLMyvKMzkly85sa4ygsfIViIOMRqR1xU',
    appId: '1:25069081784:android:5f772f0224ab10f8d6d04d',
    messagingSenderId: '25069081784',
    projectId: 'synew-gym',
    storageBucket: 'synew-gym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Vm8wP0KenUsZDROP0DD24YiNtECOn1Y',
    appId: '1:25069081784:ios:086eda4355c9de85d6d04d',
    messagingSenderId: '25069081784',
    projectId: 'synew-gym',
    storageBucket: 'synew-gym.appspot.com',
    androidClientId: '25069081784-lnu8kple4520j37s5p1pl757e5tgh6kq.apps.googleusercontent.com',
    iosClientId: '25069081784-267582jg3kiiv2kf3bptv31oalgao08r.apps.googleusercontent.com',
    iosBundleId: 'com.example.synewGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Vm8wP0KenUsZDROP0DD24YiNtECOn1Y',
    appId: '1:25069081784:ios:498fe3165d9ec9efd6d04d',
    messagingSenderId: '25069081784',
    projectId: 'synew-gym',
    storageBucket: 'synew-gym.appspot.com',
    androidClientId: '25069081784-lnu8kple4520j37s5p1pl757e5tgh6kq.apps.googleusercontent.com',
    iosClientId: '25069081784-sc2tg1riignb1bmbdkdf73sbqlev6kg9.apps.googleusercontent.com',
    iosBundleId: 'com.example.synew',
  );
}
